require:
  - rubocop-rails
  
AllCops:
  TargetRubyVersion: 3.1.0
  NewCops: enable
  inherit_mode: merge
  Exclude:
    - 'bin/bundle'
    - 'app/controllers/graphql_controller.rb'  

Rails/I18nLocaleTexts:  
  Enabled: false

Style/Documentation:  
  Enabled: false

Security/Eval:
  Enabled: false  

Metrics/BlockLength:
  Exclude:
    - spec/controllers/*